version: '2.0'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        APP_ENV: '${APP_ENV}'
    image: php
    container_name: sdk_mkc
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: sdk_mkc
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - mkc-app-network
  #Nginx Service
  mkc_webserver:
    image: nginx:alpine
    container_name: sdk_mkc_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mkc-app-network
networks:
  mkc-app-network:
    driver: bridge
